swagger: "2.0"

info:
  $ref: info.yaml

schemes:
  - http
  - https

basePath: /v1

produces:
  - application/json
consumes:
  - application/json

tags:
  $ref: tags.yaml#/tags

security:
  - basicAuth: []

paths:
  $ref: paths/index.yaml

definitions:
  $ref: definitions/index.yaml

parameters:
  $ref: parameters.yaml#/parameters

responses:
  $ref: responses.yaml#/responses

securityDefinitions:
  $ref: security.yaml#/securityDefinitions


