/**
 * ProIn.WebApi
 * This is a ProIn data access WebApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zwq00000@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The LoginInfo model module.
* @module model/LoginInfo
* @version 1.0.0
*/
export default class LoginInfo {
    /**
    * Constructs a new <code>LoginInfo</code>.
    * 用户登录信息
    * @alias module:model/LoginInfo
    * @class
    * @param username {String} 
    * @param password {String} 
    */

    constructor(username, password) {
        

        
        

        this['username'] = username;this['password'] = password;

        
    }

    /**
    * Constructs a <code>LoginInfo</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LoginInfo} obj Optional instance to populate.
    * @return {module:model/LoginInfo} The populated <code>LoginInfo</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginInfo();

            
            
            

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} username
    */
    username = undefined;
    /**
    * @member {String} password
    */
    password = undefined;








}


