/**
 * ProIn.WebApi
 * This is a ProIn data access WebApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zwq00000@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The MeasureRecord model module.
* @module model/MeasureRecord
* @version 1.0.0
*/
export default class MeasureRecord {
    /**
    * Constructs a new <code>MeasureRecord</code>.
    * @alias module:model/MeasureRecord
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>MeasureRecord</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MeasureRecord} obj Optional instance to populate.
    * @return {module:model/MeasureRecord} The populated <code>MeasureRecord</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MeasureRecord();

            
            
            

            if (data.hasOwnProperty('SessionId')) {
                obj['SessionId'] = ApiClient.convertToType(data['SessionId'], 'Number');
            }
            if (data.hasOwnProperty('SpecId')) {
                obj['SpecId'] = ApiClient.convertToType(data['SpecId'], 'String');
            }
            if (data.hasOwnProperty('Time')) {
                obj['Time'] = ApiClient.convertToType(data['Time'], 'Date');
            }
            if (data.hasOwnProperty('Count')) {
                obj['Count'] = ApiClient.convertToType(data['Count'], 'Number');
            }
            if (data.hasOwnProperty('Stdev')) {
                obj['Stdev'] = ApiClient.convertToType(data['Stdev'], 'Number');
            }
            if (data.hasOwnProperty('Mean')) {
                obj['Mean'] = ApiClient.convertToType(data['Mean'], 'Number');
            }
            if (data.hasOwnProperty('Range')) {
                obj['Range'] = ApiClient.convertToType(data['Range'], 'Number');
            }
            if (data.hasOwnProperty('Values')) {
                obj['Values'] = ApiClient.convertToType(data['Values'], ['Number']);
            }
        }
        return obj;
    }

    /**
    * @member {Number} SessionId
    */
    SessionId = undefined;
    /**
    * @member {String} SpecId
    */
    SpecId = undefined;
    /**
    * @member {Date} Time
    */
    Time = undefined;
    /**
    * @member {Number} Count
    */
    Count = undefined;
    /**
    * @member {Number} Stdev
    */
    Stdev = undefined;
    /**
    * @member {Number} Mean
    */
    Mean = undefined;
    /**
    * @member {Number} Range
    */
    Range = undefined;
    /**
    * @member {Array.<Number>} Values
    */
    Values = undefined;








}


