/**
 * ProIn.WebApi
 * This is a ProIn data access WebApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zwq00000@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The MeasureValue model module.
* @module model/MeasureValue
* @version 1.0.0
*/
export default class MeasureValue {
    /**
    * Constructs a new <code>MeasureValue</code>.
    * @alias module:model/MeasureValue
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>MeasureValue</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MeasureValue} obj Optional instance to populate.
    * @return {module:model/MeasureValue} The populated <code>MeasureValue</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MeasureValue();

            
            
            

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], ['Number']);
            }
        }
        return obj;
    }

    /**
    * @member {Number} count
    */
    count = undefined;
    /**
    * @member {Array.<Number>} data
    */
    data = undefined;








}


