/**
 * ProIn.WebApi
 * This is a ProIn data access WebApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zwq00000@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SerialModelState model module.
* @module model/SerialModelState
* @version 1.0.0
*/
export default class SerialModelState {
    /**
    * Constructs a new <code>SerialModelState</code>.
    * @alias module:model/SerialModelState
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>SerialModelState</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SerialModelState} obj Optional instance to populate.
    * @return {module:model/SerialModelState} The populated <code>SerialModelState</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SerialModelState();

            
            
            

        }
        return obj;
    }









}


