/**
 * ProIn.WebApi
 * This is a ProIn data access WebApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zwq00000@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MeasureRecord from './MeasureRecord';





/**
* The TaskSession model module.
* @module model/TaskSession
* @version 1.0.0
*/
export default class TaskSession {
    /**
    * Constructs a new <code>TaskSession</code>.
    * 测量任务会话
    * @alias module:model/TaskSession
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TaskSession</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TaskSession} obj Optional instance to populate.
    * @return {module:model/TaskSession} The populated <code>TaskSession</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskSession();

            
            
            

            if (data.hasOwnProperty('SessionId')) {
                obj['SessionId'] = ApiClient.convertToType(data['SessionId'], 'Number');
            }
            if (data.hasOwnProperty('PartId')) {
                obj['PartId'] = ApiClient.convertToType(data['PartId'], 'String');
            }
            if (data.hasOwnProperty('MeasureTime')) {
                obj['MeasureTime'] = ApiClient.convertToType(data['MeasureTime'], 'Date');
            }
            if (data.hasOwnProperty('Batch')) {
                obj['Batch'] = ApiClient.convertToType(data['Batch'], 'String');
            }
            if (data.hasOwnProperty('Operator')) {
                obj['Operator'] = ApiClient.convertToType(data['Operator'], 'String');
            }
            if (data.hasOwnProperty('Team')) {
                obj['Team'] = ApiClient.convertToType(data['Team'], 'String');
            }
            if (data.hasOwnProperty('EquipmentNum')) {
                obj['EquipmentNum'] = ApiClient.convertToType(data['EquipmentNum'], 'String');
            }
            if (data.hasOwnProperty('Records')) {
                obj['Records'] = ApiClient.convertToType(data['Records'], [MeasureRecord]);
            }
        }
        return obj;
    }

    /**
    * 任务会话Id
    * @member {Number} SessionId
    */
    SessionId = undefined;
    /**
    * 部件Id
    * @member {String} PartId
    */
    PartId = undefined;
    /**
    * 测量时间
    * @member {Date} MeasureTime
    */
    MeasureTime = undefined;
    /**
    * 产品批号
    * @member {String} Batch
    */
    Batch = undefined;
    /**
    * 操作员
    * @member {String} Operator
    */
    Operator = undefined;
    /**
    * 班组
    * @member {String} Team
    */
    Team = undefined;
    /**
    * 设备编号
    * @member {String} EquipmentNum
    */
    EquipmentNum = undefined;
    /**
    * @member {Array.<module:model/MeasureRecord>} Records
    */
    Records = undefined;








}


