/**
 * ProIn.WebApi
 * This is a ProIn data access WebApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zwq00000@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Workpiece model module.
* @module model/Workpiece
* @version 1.0.0
*/
export default class Workpiece {
    /**
    * Constructs a new <code>Workpiece</code>.
    * @alias module:model/Workpiece
    * @class
    * @param partId {String} 部件Id
    */

    constructor(partId) {
        

        
        

        this['PartId'] = partId;

        
    }

    /**
    * Constructs a <code>Workpiece</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Workpiece} obj Optional instance to populate.
    * @return {module:model/Workpiece} The populated <code>Workpiece</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Workpiece();

            
            
            

            if (data.hasOwnProperty('PartId')) {
                obj['PartId'] = ApiClient.convertToType(data['PartId'], 'String');
            }
            if (data.hasOwnProperty('Category')) {
                obj['Category'] = ApiClient.convertToType(data['Category'], 'String');
            }
            if (data.hasOwnProperty('PartName')) {
                obj['PartName'] = ApiClient.convertToType(data['PartName'], 'String');
            }
            if (data.hasOwnProperty('PartNumber')) {
                obj['PartNumber'] = ApiClient.convertToType(data['PartNumber'], 'String');
            }
            if (data.hasOwnProperty('PartDwgNo')) {
                obj['PartDwgNo'] = ApiClient.convertToType(data['PartDwgNo'], 'String');
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
        }
        return obj;
    }

    /**
    * 部件Id
    * @member {String} PartId
    */
    PartId = undefined;
    /**
    * 部件类别
    * @member {String} Category
    * @default '默认类别'
    */
    Category = '默认类别';
    /**
    * 品名
    * @member {String} PartName
    */
    PartName = undefined;
    /**
    * 产品代码
    * @member {String} PartNumber
    */
    PartNumber = undefined;
    /**
    * 图号/Part Drawing Number
    * @member {String} PartDwgNo
    */
    PartDwgNo = undefined;
    /**
    * 产品描述
    * @member {String} Description
    */
    Description = undefined;








}


