/**
 * ProIn.WebApi
 * This is a ProIn data access WebApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zwq00000@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Workpiece from './Workpiece';





/**
* The Workpieces model module.
* @module model/Workpieces
* @version 1.0.0
*/
export default class Workpieces extends Array {
    /**
    * Constructs a new <code>Workpieces</code>.
    * @alias module:model/Workpieces
    * @class
    * @extends Array
    */

    constructor() {
        
        super();
        

        
        

        

        return this;
    }

    /**
    * Constructs a <code>Workpieces</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Workpieces} obj Optional instance to populate.
    * @return {module:model/Workpieces} The populated <code>Workpieces</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Workpieces();

            ApiClient.constructFromObject(data, obj, 'Workpiece');

            
            

        }
        return obj;
    }









}


