/**
 * ProIn.WebApi
 * This is a ProIn data access WebApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zwq00000@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProinApi);
  }
}(this, function(expect, ProinApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProinApi.TaskSession();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TaskSession', function() {
    it('should create an instance of TaskSession', function() {
      // uncomment below and update the code to test TaskSession
      //var instane = new ProinApi.TaskSession();
      //expect(instance).to.be.a(ProinApi.TaskSession);
    });

    it('should have the property sessionId (base name: "SessionId")', function() {
      // uncomment below and update the code to test the property sessionId
      //var instane = new ProinApi.TaskSession();
      //expect(instance).to.be();
    });

    it('should have the property partId (base name: "PartId")', function() {
      // uncomment below and update the code to test the property partId
      //var instane = new ProinApi.TaskSession();
      //expect(instance).to.be();
    });

    it('should have the property measureTime (base name: "MeasureTime")', function() {
      // uncomment below and update the code to test the property measureTime
      //var instane = new ProinApi.TaskSession();
      //expect(instance).to.be();
    });

    it('should have the property batch (base name: "Batch")', function() {
      // uncomment below and update the code to test the property batch
      //var instane = new ProinApi.TaskSession();
      //expect(instance).to.be();
    });

    it('should have the property operator (base name: "Operator")', function() {
      // uncomment below and update the code to test the property operator
      //var instane = new ProinApi.TaskSession();
      //expect(instance).to.be();
    });

    it('should have the property team (base name: "Team")', function() {
      // uncomment below and update the code to test the property team
      //var instane = new ProinApi.TaskSession();
      //expect(instance).to.be();
    });

    it('should have the property equipmentNum (base name: "EquipmentNum")', function() {
      // uncomment below and update the code to test the property equipmentNum
      //var instane = new ProinApi.TaskSession();
      //expect(instance).to.be();
    });

    it('should have the property records (base name: "Records")', function() {
      // uncomment below and update the code to test the property records
      //var instane = new ProinApi.TaskSession();
      //expect(instance).to.be();
    });

  });

}));
