/**
 * ProIn.WebApi
 * This is a ProIn data access WebApi
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zwq00000@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProinApi);
  }
}(this, function(expect, ProinApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProinApi.Workpiece();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Workpiece', function() {
    it('should create an instance of Workpiece', function() {
      // uncomment below and update the code to test Workpiece
      //var instane = new ProinApi.Workpiece();
      //expect(instance).to.be.a(ProinApi.Workpiece);
    });

    it('should have the property partId (base name: "PartId")', function() {
      // uncomment below and update the code to test the property partId
      //var instane = new ProinApi.Workpiece();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "Category")', function() {
      // uncomment below and update the code to test the property category
      //var instane = new ProinApi.Workpiece();
      //expect(instance).to.be();
    });

    it('should have the property partName (base name: "PartName")', function() {
      // uncomment below and update the code to test the property partName
      //var instane = new ProinApi.Workpiece();
      //expect(instance).to.be();
    });

    it('should have the property partNumber (base name: "PartNumber")', function() {
      // uncomment below and update the code to test the property partNumber
      //var instane = new ProinApi.Workpiece();
      //expect(instance).to.be();
    });

    it('should have the property partDwgNo (base name: "PartDwgNo")', function() {
      // uncomment below and update the code to test the property partDwgNo
      //var instane = new ProinApi.Workpiece();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "Description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new ProinApi.Workpiece();
      //expect(instance).to.be();
    });

  });

}));
